// <auto-generated />
namespace TrainingSchedule.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class userEvent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userEvent));
        
        string IMigrationMetadata.Id
        {
            get { return "201408261540573_userEvent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
